apiVersion: ENC[AES256_GCM,data:Re8=,iv:29/dh1+ifxd1d5yr01WFa/GEu4MBR/u7BSqLeNe9qjw=,tag:jqe2MlTwERm/xX/BD20Gtw==,type:str]
data:
    valkey-password: ENC[AES256_GCM,data:1iwPm+gyinXsui+xGnHBVw==,iv:4ls1GR2sSsrNtV/FsQzL4BOa667K2YdD8aVqIu2srUo=,tag:G1c67C+ckEodvTqzAtKO1w==,type:str]
kind: ENC[AES256_GCM,data:Qja+Tr0j,iv:JdCeyghmxW7TRN4bGRTShIZP6ixfjboe/uYZ7JjRB6Q=,tag:6J7WvqIu2cliDsPmtY0bVA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:IbPkdH5x1q+5wsv9TA==,iv:mS0f4d0AzUjxZUirza7Qt7zppx/XsKhJ2UQfdvNJ/3I=,tag:CvD164vUCSWfQTP3ttNZMA==,type:str]
    namespace: ENC[AES256_GCM,data:vPFqr+97,iv:8eW52ioYoECvVeQSWVvS/1vuNtGJ5XukMWflYRPF/5g=,tag:vZ3rpHnrPeGFxhlAvGVybg==,type:str]
sops:
    age:
        - recipient: age1dmaj620d54n0euwe2fz6lg2vvfkwwt7gtj6t5r9tqmsuj2ah0cpqg4dg7k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqemJoT253emJkR2VPampV
            RG50NTJkYy9hN1Q0MzBWdHA1K0s5RmUwU1hzCkdDbmtibDFPNzZWYmFSZ2Iwcjc2
            aWpRRlBVbVJVcEVuM3N5UEhHa1hZOEEKLS0tIGNKSDA4MTB4a1pZT3hXeVVyNmZp
            WUVHVE1jTXBQRHFtTDlFWDZKSkdsVjgKagQkIA1vAj/863//W4ihMERKHoC7GuVK
            3tzTO77UwTvOhuNyEyf9foglnHfIWn7r7Sk+cP74w04XV6UKQ+Ic3g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-16T21:54:27Z"
    mac: ENC[AES256_GCM,data:llqDbLoosbBCPwxtCx/XGM1EEcA7CQbwpkgPrq4alztGTjLS6awsKVJMVyz5ytu7Hjne6sqOGbPKxSPDz9a01Mkvw+t6lBM5D3kZAJAJhO1i/UJKxWC7QqFPN3LeYxym6tE2U+Ne2Z98yLSCPMaaKYCe4YxwIoj3PZPmTyw6LXM=,iv:0ysp59m6QBvlcWIuYO5B3YIdAFrVy1/dg/POxuBxi/w=,tag:1DId+mnC4WY9M59y/rom8A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
