apiVersion: ENC[AES256_GCM,data:DPM=,iv:wsEybppnGQ7N/PkQnF7fVDQ4gH254+N2OW7bL6Wyb8g=,tag:xTKgS5/RK4BBEo8iJOpIDw==,type:str]
data:
    .dockerconfigjson: ENC[AES256_GCM,data:sLKRDrtI0tUfAwdU2tN1wJxkATubND2uUsFBE8xgB/Rfhh3kSf7eL9/KZ/mTbsgX/g+Pu44un5Vx1YxXf1lcx45wgcbp9tXZbwmufooP5iqAxjSqLQ51SFmEH2J739r07K0cYKzl4oJZy1RQWPhhYcH8SD2rxmvc1H2w2AEtARxGKzn9ZEZG7Hf42zAaiTfp4gukjztGSNu1rVBnf/RcQPAwNjtmu2IzvmPWYl2tht5zVlg1jjizcEFcDCPC7wQoNbmtUNSfnVAzQG7SvySBRZprBpNUmWc3VzPMlMEVBU/Wee/S,iv:ewsrMCkJWOZoXizXN5PZqoWpvNe18ZI7AgMFkCEtnFw=,tag:IKO9fug+FkRe0MKccsaiAg==,type:str]
kind: ENC[AES256_GCM,data:f/VxHR8x,iv:rhaK8mLgR1M5ngtd9ZVEQ1RP4qkKapdo52vrEtwYBG8=,tag:e026hGUgPwIP8KJAE1POVA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:uId/0BVXWxseDw==,iv:ty3qtV8G5xP7Iur7DjwiAjPCEwT8t9brjVPkNK9f1Zc=,tag:6XhlFS5A++88Kx0soVKz7Q==,type:str]
    namespace: ENC[AES256_GCM,data:xU0rYMayCObZ,iv:+s3UrcaT3fpXusd/z5nQB2QjQAH2cEcu/ZQRG806+Ng=,tag:AhB9/WKR6i3r6oZTiuF+CQ==,type:str]
type: ENC[AES256_GCM,data:sCX/l8+W6K2hzCODQlyfYU725T2lk9mcHiBlAMrf,iv:h0XGlUs2Bsmup90bZ9erTXk/xedVpWlZDlRiIt1BfTc=,tag:BMSs06HlrY3ho1Pv6DkM2Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHZk1kVE94VTA5bDdwbzhS
            ajJ0YWRlVHJYNHlUR1hEbStHMUtSVlFva0JJCjRDUjNxd2w0OGFLYjRJNXFUTWFS
            dTFjcjVIK2sxYUNkb0VjTVBtT2xLdncKLS0tICt6M0QzdTVZb0FERFBNL3B0eW5L
            L01yVGpDVDFWUWhsMElTNmZKVWtwdDAKeVO+mM21nwEQJErc7pBhNrHuDLqxr5PR
            /82xqeTgNPccY8wHPphHg47WS5uGXbMaVDfYlZ3aWKmekUK+D8mynw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dmaj620d54n0euwe2fz6lg2vvfkwwt7gtj6t5r9tqmsuj2ah0cpqg4dg7k
    lastmodified: "2026-09-28T02:52:13Z"
    mac: ENC[AES256_GCM,data:1sptUkFD43PLZ/53YZx47l1i6HAHV9kc3TUw08lOSOVf+6qJevgpAKCEnxIttz61DyRN6nfifFVueU6ejh+x5W268SVZMn5l+PfA5opfTHVrViEe3Yj/aIzRdvGt1qHHHPkmJ0EWmA+eSYxWFu0/UOWJ6Ye8zgR+xKzUDAMlQfY=,iv:aera6I+GHlBbh8Rg6xM4vXkkIix8jYnUvK4zO5MT2+E=,tag:CUSGtgcKta7LqB4uUTmFqQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
