apiVersion: ENC[AES256_GCM,data:llI=,iv:Z/fQlAuHx4klkfYUm2IUfpsyJ69hjjMVoZeX7MshUj4=,tag:gWQxjeaacS4jWyhMPJlyJg==,type:str]
data:
    .dockerconfigjson: ENC[AES256_GCM,data:Bqqr1aI9BIt1I73aPZtGWBvvynHyNtDeWZEJkXvLOzelqnSoLQ5qcHY7NS9JqRsQIhvglZWnz/+Pm44R2wpchw9jIV5lyArrGQCBSC5eUAeiqPB3yuq2fNAEHVX/6PpuiPM4LvppfvBENNf7je680vECgE/yDmeSdJj+F0lvibNag6wAcNalmjna3WQB6hjTGfaQqMqEk99jPK5ggxJEFBHcLxY6tUR/5bbkoXD7G01AyBaY7u+Gml/y+pP1ZNfKEVFNWRm6GSKKQ6juHgpwFRi/PEV5v0zQn3jxaFyUagFN/sZq,iv:k2YX+4h1wf773wrVhCZObYQmRKXh+2w0wiASZYUvQEo=,tag:1m3OXAfRp8olTK8pCW1T1A==,type:str]
kind: ENC[AES256_GCM,data:830gLsO1,iv:psmQk+7A2L0faVVhu3UUmCxIVV1lTi+9hhGtH7PDQ34=,tag:YIV4ZweTeGwwD5xS4Fu81A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:bJOs+oaBD8puqA==,iv:DrnSDSLO30yL8JfNlz+mmA5RNZSMnsWw/j3wMJQg/yk=,tag:asH0IPMAx18lHQofxT5LRw==,type:str]
    namespace: ENC[AES256_GCM,data:Sh1XyYXHsJ6l,iv:a4olN13+H+w3G5zScPmG2JfDjcRctWlb2iwozgaQKQU=,tag:jd8wSpZ6XL1YqI4IXbD1zw==,type:str]
type: ENC[AES256_GCM,data:gewZnSohwGwkWPsyBPE3uz8UUGrQt89y+3fJ8qBV,iv:Su45foXkyiiEe5iyUqnZkB4ukFFNmUHYvUsIy2/uzJo=,tag:TVFge5f7LQ2+aqAOWdvQxg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBydnN1SjNrUWFrN2hLbXNL
            RXdCNGdEK0h2d2tJOG81R3l6eHN4YnNNRFFBClpwMnhpOHcxai9KSmlmU2c0cS9I
            T0psTnZlNzBCTGZlbmZZc2d4ZVllL0UKLS0tIHdyeTJwRFZIZG80dmhvWUx0Y09M
            YkdGeEtvcDlEQWc3bmhxUndUZ2pnQjQKnaRBTjvQ82qAFUryntxTrORCjFqGmJFT
            K4R1fINomheakOnYqh89kfSBdkgKUSgod9jtYbrBN1DeRiBsoHho8Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dmaj620d54n0euwe2fz6lg2vvfkwwt7gtj6t5r9tqmsuj2ah0cpqg4dg7k
    lastmodified: "2026-09-30T03:00:32Z"
    mac: ENC[AES256_GCM,data:96447KnUNxexm3WcbNpoJqNu6QStK05HaAoysNX6ZvaQfLLmSgAZJ8f47j+MKQFyPkRyLo85HDIH1XbVELJU7xVZDsNyG1wJ/b/vyYoYtWSdRDkyj6Lya8cyjwHQBr+XupUASnhH+iCr5pmUgQc+7eCdlMzQV/oFEHfEqowpFEE=,iv:Q3p88U3QC4750+4DNc69/mV1dQCW1ZdWYF+jdeeuNT8=,tag:i/djGbLFomoRu2Tuuendsg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
