apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: user-service
  namespace: ecommerce
spec:
  interval: 10m
  chartRef:
    kind: OCIRepository
    name: user-service
    namespace: flux-system
  values:
    replicaCount: 2
    crds:
      enabled: true
