apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: payment-service-kubelet-probes
  namespace: ecommerce
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/instance: payment-service
  ingress:
    - fromEntities:
        - host
        - remote-node
      toPorts:
        - ports:
            - port: "3003"
              protocol: TCP
