apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../base/ecommerce/payment-service
  - ./networkpolicy.yaml
  - ./ciliumnetworkpolicy.yaml
  - ./payment-secret.enc.yaml
  - ./order_database.yaml
  - ./payment_database.yaml
patches:
  - patch: |-
      - op: replace
        path: /spec/ref/semver
        value: "0.6.0"
    target:
      kind: OCIRepository
      name: payment-service
  - patch: |-
      - op: replace
        path: /spec/values
        value:
          ingress:
            host: payment.home.kevinbreit.net
          image:
            tag: "0.5.0"
          imagePullSecrets:
            - name: ghcr-token
          envFrom:
            - secretRef:
                name: payment-service-secrets
            - configMapRef:
                name: payment-service-config
          database:
            host: ecommerce-dev-rw.cnpg-system
            databaseName: payment-service
          orderDatabase:
            host: ecommerce-dev-rw.cnpg-system
            databaseName: order-service
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
    target:
      kind: HelmRelease
      name: payment-service
