apiVersion: ENC[AES256_GCM,data:bGY=,iv:alK5M75FU3Vf8LFfIolASo3Oq6/i9bdMjzzykxwcc6E=,tag:XDsM/lVEryWtmFQqw0AvtA==,type:str]
kind: ENC[AES256_GCM,data:wWO0iLiS,iv:LII3Gg97vvoKNQN0cD/QEhHJmO1Yh53IpuseanCsGnM=,tag:l2WkbNaabLL/kk8i351JGQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:vtc2LiCrDHEmQ82QBu88xW5pLlBiyD4=,iv:ywWpdJrK5V7wLsSlhy3+P0lEVFrtt7VGiD23K80ZgWc=,tag:uoOBbpxOQs9fKzZwHMAi/w==,type:str]
    namespace: ENC[AES256_GCM,data:M6p4B08n8Qho,iv:cHgRuuqLh7XCEwhYcUFnR5wJevioxhofixr52vr8Yo4=,tag:lfyexawid4kt5SdfE/tYXQ==,type:str]
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:XAwYUKsDGTQRNBbeljrRzm/Q/D0h5L5ybdw9uXSgVm5ln+bmchuUM1hseFjg8Y4Tjow7FovnBMkx4FELk+BRWg==,iv:K//ukscz434tkaw0toIq8pD1fymdsd19diOd6sj2W3I=,tag:Q062BEu8BBsxrmoJkiRr2A==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:F6Vy3KklP2rM,iv:zIh+U2hEt36TjiYu0M4Mvv+oZgzwiNBIQ38VQj5Nlvw=,tag:eiiyT7vb3Kasqc2vqOPWMQ==,type:str]
type: ENC[AES256_GCM,data:UpCWHIHj,iv:db2Sf1OEOe64g7cZvtz42udKzpykLb/85tE0VCWF6dU=,tag:dpZ9BZ8Kx3s/GLAZDwh4kA==,type:str]
sops:
    age:
        - recipient: age1dmaj620d54n0euwe2fz6lg2vvfkwwt7gtj6t5r9tqmsuj2ah0cpqg4dg7k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUTTdvWWQrL1doSjJUQngz
            UEYra1RBOEVIbVBYRU82MWwzcnp1NGM1V1I4CmlOVlVBNHBSZ2h6dk5BVllKcFli
            NWcrWnNtNkNteG51NzNYL09sV3liRUUKLS0tIEZHaUFMcXhvbHBWNU8rb3dCZFFt
            alk3QWNmTVduaStveVVlQ2ordmF1WGcKHVWYMorIL0vK7pA1iuQ1QNlKOADoCpsi
            RTVAvyBiWaoGczhM02Lmafp5qy+22q+9XsJY9urXnSQwHAl+ehWahw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-11T03:17:27Z"
    mac: ENC[AES256_GCM,data:MrOtPDr4urDC7deNXvhm094Hmbc0TlIgVmDbooQrT3k5oVDdy1PAaATSdlQ6ev0eIG00oy9VLoEKN+jabXXFhPpO/CLI1ee4c3WTKYVPxHDgn2gwhOSyJXMJJWFVzR9R9qvyqkK7fBk2DhDH/tWQ+51KTj3td2IYJUcehKXCLrY=,iv:b3moHTgrEyDctClqr+PVB5rXbL7r2RIdacb3eV+TR9g=,tag:OQrLJT7LSjlEODMLrsL2jA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
