apiVersion: ENC[AES256_GCM,data:Nx0=,iv:gwiwOPnIjTJgP9rchFpgtMhNDnsCv/ojtxUbGpuSjyc=,tag:wscPYUXVUACLDKzenvGWdg==,type:str]
data:
    DB_PASSWORD: ENC[AES256_GCM,data:8ycwsWopHhaunanE7GE2EyDcWQtAHsxxc22EyDyH0VsMrr+7XCGyVieiwLfobwh6hIjMY0iSpmNdFMS0uPHX0w==,iv:zLA5mwnMMYuR0KIJClmnnLat8FFIs8JEMdBCr+6cyZA=,tag:NfLtPIj6HWBlTggi84LFGQ==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:FoiigvJlgnuRxqdP,iv:RDlCcccUcQET1B+2VaL8NLYZZ0fSdZX+83wBiWev+Ys=,tag:nW15JA27oqineU8yUQ/MkA==,type:str]
kind: ENC[AES256_GCM,data:i0oanXkG,iv:3kGEr7geQxqkDqcnfxOt3CzXzpFxLyq3tH/TBPT2o0k=,tag:OLdkU+HW/jzIN9Y6DPTqcw==,type:str]
metadata:
    creationTimestamp: ENC[AES256_GCM,data:9SPdKpsAMlexC4HTT/O/b3iz7ZI=,iv:k/jI7wNyWidCSBnJ9e3ORoGCSeLovd0IhuQ3jYGaLqY=,tag:zh6bcUfeijNjHuV5lIqanA==,type:str]
    labels:
        kustomize.toolkit.fluxcd.io/name: ENC[AES256_GCM,data:vRtTmHg7Ezw0VeQ2psn70VbFPcUFj9X+rjBAfUiD,iv:BSZ4uOYX4EGTfoMgddVuRsyPnxIUTY+Io0kGa5lof+k=,tag:tSa6FWWUBk9O0AZKJ/ZFFA==,type:str]
        kustomize.toolkit.fluxcd.io/namespace: ENC[AES256_GCM,data:6JVWqSO2LsLO3AE=,iv:YJ7ddlpJdX9/P9M/HRnsZRYlB+3YHJTDjjEzCF7WSpw=,tag:SDcPXIjoH8pV2rEl2gHrcg==,type:str]
    name: ENC[AES256_GCM,data:aOMP8Ta5Jrlk2zwYNsgyslp4DgrrJBg=,iv:aTWk0717tEtu3vDTHVGbSEKQwa6mRc5JZsOttluy//o=,tag:tQddKPrt1NbY7uohjS4QVw==,type:str]
    namespace: ENC[AES256_GCM,data:fMXlJWzd/0+G,iv:F9UqIojf223TW53CziqCu6vmhrHtcbHdp7cGRUaulvo=,tag:8TYcZYaBUYhn0g6A3XrX+A==,type:str]
    resourceVersion: ENC[AES256_GCM,data:WB56L7d3utA=,iv:1QHQPhb0djYvOgAoka6XRxhlgElVdQqo9emtK0f9mow=,tag:mL6uYQYJIevYcmqmY6Mr+A==,type:str]
    uid: ENC[AES256_GCM,data:QbV5CbrQDx4LLSP9CPsKBUVXOuNbiEFmdv/AFv8jkHg5juIS,iv:QMMrWZUJPSFG5s4dgKxiDPMDLBmZD0Zd1qwDJf6cUjI=,tag:XbKit1hVvSzNqYGmI6ba8w==,type:str]
type: ENC[AES256_GCM,data:cyCGMb/l,iv:13p3JuyYL+YCFAqlNp7lCSk6cuyT7eX4Yfi33I7Wces=,tag:Do2SDWlFzF2JdblNYJTJkA==,type:str]
sops:
    age:
        - recipient: age1dmaj620d54n0euwe2fz6lg2vvfkwwt7gtj6t5r9tqmsuj2ah0cpqg4dg7k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsMmQvWGJZQUhFMmxYekxl
            U1djZGl4ZnBMcFBpUzJBVGhoL0hNaEVQS0hnClNiWC95TFNiYU0wbUxGMXBGQ29s
            UkpxaCtEczlveGJ0NlFUdUtkZC92cFkKLS0tIGF2TldSZ0tEKzByY1BoTzVYOVp5
            RTBzUkQ5RWYvVFFHVDc1bGNhOHRkZFUK6ulVkKGfK08D5Ni/2B3zv+ijM1h8PRwW
            yZG/5LMgZHs1SR+DNh2YBw783btS307+M4XlMKBFOPRSFnSGz4lhDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-11T03:10:53Z"
    mac: ENC[AES256_GCM,data:u0IWO3HcjMpch6LmB46CEJH5Wud3qrY/j2iRZAp61iBsnEM7DYuqIOQT8G1WGfmE2Sd5iFYF+yC1PBdSbrcog5BPSkYFqz5XmU+XlNOESd9PP1k8frFCdiFXsRSnojEDpE3Ibh5WODGkYVFJUilIDrfFUwDU3CHmwKz/zBmg4ks=,iv:FAWzzaRXR1sKDaHnoDfuF+Km7V9fIZAsmr7cP9nzgVE=,tag:8QDU0OsVws4mL1c9G0iZ3Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
