apiVersion: ENC[AES256_GCM,data:+F8=,iv:RuYPqNSXms1zj9Fyv7OM/yyc/sVvh2F4pLzfjpEj0mI=,tag:M3rda8GtcfTsUhK+Lpb20Q==,type:str]
kind: ENC[AES256_GCM,data:tWubpb0T,iv:6Iuf0AncLJQQZkf/crW4b53dZTCoapFyjsiTq6SML3c=,tag:vHAGgoY5MWPjDwrFFZ1znw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:r4IcwxKNOjrAAcAqrdmAUkaWR+zi1To=,iv:xWyVCtJ5HrQNxKb7G1P+cCFnAgjem89bhKUYQZc2xRY=,tag:Hy/iaMlX0x4ORi2X81aqQQ==,type:str]
    namespace: ENC[AES256_GCM,data:skkzfeHCnTU9,iv:gESO4uPoQylJArTueEgXKD0dC3oxHmEGi5FMcIAjSFA=,tag:7mXHWkUuxB9+wefbN/znPg==,type:str]
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:R0USPWvPYl1BPl0/+tphVScObHkTYH8TbgADlx+2gBRiFFOksF1LhqKoZ2v5bqWBhDZaCeQ5hhkNKp878rzYpQ==,iv:dGb3uROserEJhiDjTIEXJmKe8KRYwcxDzWzKhpmXv0U=,tag:B0/wLy6zvQ3kye+BUQp1FQ==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:bgy0,iv:3QJas7Dg7PLc0+X3Aba9kckquRQSXCn9TxMuNJ/wQaA=,tag:8g5cTbb1j24W9fbBEWdv+A==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:/5dDwAvhJGBf,iv:cHrTS93JmFsA1gJkF6iH6XRPnq3cvF0hgZhzL+dmD94=,tag:320E7Ky+Y+X+f7Uq2WMycQ==,type:str]
type: ENC[AES256_GCM,data:ywGUrwLi,iv:Y6zBCmDGhouvrKVXzzEOVjYpyWedyj0wUiNIhiKwHDA=,tag:NkbxoPx6s2jjGEavjY/a2A==,type:str]
sops:
    age:
        - recipient: age1dmaj620d54n0euwe2fz6lg2vvfkwwt7gtj6t5r9tqmsuj2ah0cpqg4dg7k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNRG5zYVpOTk1BS3J5OVRz
            QlNqd2RFN3FHbkZjQk4zVC9UWTZXQlFQazBvCkhnZmFLL3JuVzdoQ25KaWxlRnhx
            V1pHRWNkcTVmck45d1ZTK3hGQTUxTW8KLS0tIHF2cnBhbllPcUExSHVzQmJkZXl3
            dXB1RkJpZzR4bUgzdWoxeVJSZ0szT1UKzFVAuAOQFJ+ATsiZPfgBJzVMIHYgs+Ox
            m8c/YnJhLHOkU83kJGIN0XQs2OiHi89tOfn2cx6YjeWMxiyxrg8gVg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-11T17:05:28Z"
    mac: ENC[AES256_GCM,data:JvQNqzVwcxUPSd4TO9GbOEOn26y9lilK+1V8MCxQw5W1LxottgomrZwj9fnfn9M6NnJynb+mruws3Nunp9gAFXGo9H4orrKpP+7mbVQKjoQL6swPFIhXq9uu9GYtSQubWwHTIXfryg0q3s/auQumNMqx/FbxafOoU83IXk7z7zY=,iv:rYhNiEaoJluzq7+AL0EAimVERxbI7Uf4+VMqDGISLCs=,tag:58en0/wDUBu8wsHWA1EO2A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
