apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cnpg
  namespace: cnpg-system
spec:
  interval: 10m
  chartRef:
    kind: HelmChart
    name: cnpg
    namespace: flux-system
  values:
