apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 10m
  chartRef:
    kind: OCIRepository
    name: cert-manager
    namespace: flux-system
  values:
    replicaCount: 2
