apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 10m
  chart:
    spec:
      chart: cert-manager
      version: "v1.19.4"
      sourceRef:
        kind: OCIRepository
        name: cert-manager
        namespace: flux-system
      interval: 10m
  values:
    replicaCount: 2
