---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-cert-manager-config
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: "./infrastructure/overlays/dev/cert-manager-config"
  prune: true
  dependsOn:
    - name: infrastructure-cert-manager
