apiVersion: ENC[AES256_GCM,data:hEI=,iv:oanMCpYupiIPQshXz1zFYXqNzpZ+HGPyrswUAjs6vH4=,tag:6IpsvxGzkJk83RiMxekdnw==,type:str]
data:
    password: ENC[AES256_GCM,data:NcaPnXNxAoz4eL4j8LvwWQbQVlekX4tyPQfyElLJEfegDelr57w+8QT7rkWHdoP0JanpOuQ2x3Q=,iv:Nw91tsy7lBat8Cohl+rz1/FwLCQc3Ks8As+jqPfNds4=,tag:C0rkiw9OPeHBy+MIERePTg==,type:str]
    username: ENC[AES256_GCM,data:bo2ANA==,iv:aTMB4E5wyYclioMuCQxdIeOw+LAVXZKlGkXItZOfrvU=,tag:tD2wYvAO5JjAMUB6TpSwWg==,type:str]
kind: ENC[AES256_GCM,data:d2qfSk0w,iv:iUyegMrmiaQf9S9XUDjdg+Kuml9dlh75yNjzOlMlcxg=,tag:Ld0nFzQSkwzxQW4UQfc7nQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:JZW5gSML/IgndzpakDnzr0CYJvU=,iv:dV2ieDERnSmO3TOMwujgAKNlpxO407cirYt6ASEPBEA=,tag:/zgd02e5TCmjBDQRig6huQ==,type:str]
    namespace: ENC[AES256_GCM,data:H/gjwvSKQsgx3zs=,iv:X7DIjzlF0MlNNYeWBgL8xskk6hpt0NSwOogF8KE5sS8=,tag:R4O+q7KnZ45GqzBHiA3wbA==,type:str]
type: ENC[AES256_GCM,data:xW1tsCwrvsXQra9ATkgJRPaERDbVY8q+,iv:tK/aLwGNJq+p8SuNmFsWKSEJzrfxUlTGb+/zM85J+C4=,tag:FsMnxxuCwgAXIZGc7533wQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjaHhkaDgrL2dud25ETFhu
            Yk9HTjUvK0ZVS2RXRVNZYjlXVjV3aDNob0MwCkNldXZQK0dCeGF6VG45eDdiV0Zq
            Y0k3YUphTzJJejBIUGFuVDY1Nm5DM0kKLS0tIG1FMFRFODRCTVU2VE4rNEdIaDRP
            MGVEbkljQ2lUYTk4cmw3RWlvSkMrRkUKGzGU7vvniaff+ME/278hvdjZYLEFuw02
            hx1qr/Og62fWZDN7eGUYVlvTF+t0mDkFtXCLVW/9pvsbLOgDgtURfQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dmaj620d54n0euwe2fz6lg2vvfkwwt7gtj6t5r9tqmsuj2ah0cpqg4dg7k
    lastmodified: "2026-10-03T01:51:59Z"
    mac: ENC[AES256_GCM,data:rXk8cqPqYhVjujEVu+UjYsLcxxpelRqC0uG1qy7zsgclH3gdRWS3VNrzkAweLxr5LwWH76rz/dSq0x3n2H5+DxbUUmhoMbQzi/d+2YSEtzebSZTaFjFKp0Jyx5/HCzqgq/9wE92xFnZyEKkuQQKIrVO7VD4DE5YN/+HcFi79gdM=,iv:S0rta34ioyXywo1f/qrpEdaN/SeU5rbY0e+bSmBubNM=,tag:0p3vcxYZOj9fX6fbhl6jUg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
