apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./cnpg-db-secret.yaml
  - ./spire-db-secret.yaml
  - ./cluster.yaml
  - ./database.yaml
  - ./helm-repository.yaml
  - ./helm-release-crds.yaml
  - ./helm-release.yaml
  - ./network-policies.yaml
  - ./rbac.yaml
