apiVersion: ENC[AES256_GCM,data:8Ls=,iv:avZiQLXN+76cIcSIZQ3Devp1MdWQTE4RwqN7Wk+rE+E=,tag:ZeM6W0XkD4iqPyI+WMYWfw==,type:str]
data:
    password: ENC[AES256_GCM,data:GL/NaOVM5zN4D83eixXgJI1KZSQfhV9dVmA3tXvPRHPb89qEa8i+VfOdcVY+YQaFuX8OYay7u5A=,iv:F+iw073Sb4Vdmy1/D7u0ZtldeLZUG5EoskKMbUGabsI=,tag:hzvQSqjP+nbqmKXDMBvV0Q==,type:str]
    username: ENC[AES256_GCM,data:gNOScw==,iv:hAQaNy3UWp1wGySvL7l0B8toakQYtqw2mKYJLUTvk3E=,tag:r972YsiHRTlSONxV80TgUw==,type:str]
kind: ENC[AES256_GCM,data:ij9VdxZQ,iv:8/lsEi5304/N0/aldZzXlNCVzpFwmyUEAw5yy1uhqLs=,tag:aEnLCmvHtVjwfOCv4Ek+EA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:dcyBd7fpghrGrz+MSjPUext0Tek=,iv:8KpXOv/T9lxQWgXCmcymF7HLjABF/BjYs9XzxpkzoNA=,tag:EKOxDnlYlj78qfnIpW3mbg==,type:str]
    namespace: ENC[AES256_GCM,data:7BqYQoLWNhIbaaIX,iv:j3aWbQobxfYI6u0dqfUmLFH/woA+UwYOeq8oZ2mZ3cE=,tag:bVQm0soUF+5obotdzU98Ww==,type:str]
type: ENC[AES256_GCM,data:4KC9HZ3XwCLDq4IAJTead9q5gef5Ju20,iv:BrWP2BmSFREdMSzqJqNfBlpsXLcpHsdV2QoCa1BhKPM=,tag:8LvGn+NGlAIFQwRyjZg6XA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2OUJvdXByRHUvdDBlbHZX
            WmdBcUhIWHN3NnRRVzk0WnRIQlg4eGd4MVZVCk5tTzk2N0ZRcTVMRVhNWGpxM0NF
            LytVVURjRFQrczlndS8wYnJXMmY4OWMKLS0tIHBPTHZ5K0d0N3dqcnUxRm1LeUNn
            MnZPZk8wa2xIdVRGaDV5M2orVXA0eTQKpSBXJfXieyHL+I51dwUbuBK81b5GT8Pj
            5bPQy8J8Axzs5LtEOzfjYNeH9qZ+4IkC2OHUIN3yu4pIsHdRFpKy7A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dmaj620d54n0euwe2fz6lg2vvfkwwt7gtj6t5r9tqmsuj2ah0cpqg4dg7k
    lastmodified: "2026-10-04T02:21:57Z"
    mac: ENC[AES256_GCM,data:kzeiaZfI4OwUvYvSmG2xNTRWlPsg6MhDw+G3V7w1+GgUHM7Z9J8QZYy+fTO55nQ7GSE3dEq6/hGOxTrJXrRL9cArhf7qcch97WJa3WUg9NCdt+SnomtMHlcL7IFM2L+AZXPBdVonLbY1L9N9lMCmamFeWy1ZpW5WLGJ9QMWP2EM=,iv:LtxHzMXBpoWyzLO/9WfpR35sUKmUmU5tBA7p7Y1KFmQ=,tag:JQ5He0hThWdEXLPeqPj5OQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
