apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana-tempo
  namespace: monitoring
spec:
  interval: 10m
  chartRef:
    kind: OCIRepository
    name: grafana-tempo
    namespace: flux-system
  values:
