apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: grafana-tempo
  namespace: flux-system
spec:
  interval: 10m
  url: oci://ghcr.io/grafana-community/helm-charts/tempo
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  ref:
    semver: "2.0.0"
