apiVersion: ENC[AES256_GCM,data:6XQ=,iv:Ez+7O0sJCMmSPkvJIYT0zOMv2PuIms0mtHeBdCFHkwE=,tag:JZFw58b+hNBDuLs1pB3sjg==,type:str]
kind: ENC[AES256_GCM,data:T9+t0xVb,iv:dPqtzBAdDmA4tDwjPb0PxZVeqgVR8M75eExdOaOv0fk=,tag:yegS+5z5va/UH42lfpJZ2g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ZnNWbmk16McubaBYy5JNIys=,iv:8isQub6w0JQoczU69Ch6gEYt4IjS60dH0GTRYVoIUMQ=,tag:X23me6joVTqlaDGc5klcSQ==,type:str]
    namespace: ENC[AES256_GCM,data:koKTWuBQfR9dlA==,iv:ins/JkKrdX7Y66UQdK1vm8gTFUE7a+yIm7iUtSRDFj0=,tag:hM6Bz4OXcej2MjmcNDNE+w==,type:str]
type: ENC[AES256_GCM,data:stDFuVa1,iv:KdabZpdPupCxvLHtfERS1avq0yoDoG5ClRAGYnm40xw=,tag:zn+dIFAxcuDFWrsBSi0iSQ==,type:str]
stringData:
    password: ENC[AES256_GCM,data:+2yex2w8Fa4ys8Z4jSzXpQ==,iv:Ktesr+2RFLXDugcsoVjf6wY8UMjYzQhaZbjibjWKg5g=,tag:7OzJ+R+dxDMeIdOXLx696Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLaVpDVlk5dkNRVFFEeUFo
            M0hUUUJCNWNBUWRyUEgvcHh0SEZwdTc1YkNBCmo5cUVoVEQ5N2Vpc0FFYmNacUdM
            SWxrU3FOUFpKSHR2dW9uVHB1enhlV0UKLS0tIHc3VmZJYXVrQWhYd0xyblJTaHpv
            eVVqMWxFdy9MTGdSMWpWRWhSTVFkU3MKhkOY1dUcS7BVOAuvh5DMOAt1am1HvOx2
            vrpruwMwdWSJ1wn8j9c0V2UXKEdQib2izCJa92aOQfv3ampLs9xU0w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dmaj620d54n0euwe2fz6lg2vvfkwwt7gtj6t5r9tqmsuj2ah0cpqg4dg7k
    lastmodified: "2026-08-10T21:42:04Z"
    mac: ENC[AES256_GCM,data:K3gFFN1d3gOrc25wtPk6eE9Eny2DQQ95U7Vwy1ITY5i0tGNa8Ey2avAUlY2CrBVtJR8bg1HfbHUl8nTy6bHInntq4W2XZQnEijJrunF34P43UgK5I+PqgV7VtE/1t6MDRT2uESE3f6htzpqOIKTWQwfz8glkIWs/yeZ03k2lwzE=,iv:1D1KVXor0IUS9y1GVybizC8xeBC+njLmiEbyIsuer7o=,tag:79ohy6IK/LJRz4r/G9B1eA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
