apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: spire-selfsigned
  namespace: spire-server
spec:
  isCA: true
  commonName: spire-ca
  secretName: root-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
