apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: home-network-tls
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  interval: 1m
  module: http_2xx
  prober:
    url: prometheus-blackbox-exporter.monitoring:9115
  targets:
    staticConfig:
      static:
        - https://synology.home.kevinbreit.net
        - https://homeassistant.home.kevinbreit.net
