apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../base/ecommerce/user-service
  - ./user-service-secret.yaml
patches:
  - patch: |-
      - op: replace
        path: /spec/ref/semver
        value: "0.1.0"
    target:
      kind: OCIRepository
      name: user-service
