apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../base/ecommerce/user-service
  - ./user-service-secret.yaml
  - ./networkpolicy.yaml
  - ./ciliumnetworkpolicy.yaml
patches:
  - patch: |-
      - op: replace
        path: /spec/ref/semver
        value: "1.8.3"
    target:
      kind: OCIRepository
      name: user-service
  - patch: |-
      - op: replace
        path: /spec/values
        value:
          ingress:
            host: user.home.kevinbreit.net
          image:
            tag: "1.5.0"
          imagePullSecrets:
            - name: ghcr-token
          envFrom:
            - secretRef:
                name: user-service-secret
            - configMapRef:
                name: user-service-config
          database:
            host: ecommerce-dev-rw.cnpg-system
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          startupProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 12  # 60s total startup budget
          resources:
            limits:
              memory: 384Mi
            requests:
              memory: 384Mi
    target:
      kind: HelmRelease
      name: user-service
