apiVersion: ENC[AES256_GCM,data:qPE=,iv:wG5k8S5O1D1S+cCMaDHWntkjNh7V2/hqoMzWs7poK18=,tag:KASqCJ8D3VA0o88xj+tJww==,type:str]
data:
    DB_USERNAME: ENC[AES256_GCM,data:Mz+2pA==,iv:yOvIYB/JWfardyt/Scd+7bbNxlGfQA79pC2Onq8Js4E=,tag:7d4rSKKkZI8R7BoQiZ2B7g==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:sOn/orhD6ZSCZKM1zTqNVdbMoUKKB200V+yC0c6YnzdDZvt70raaZc/+lhwhcX4o1+DCSqoPJBkxSVu3gDd0h3bo2UfJK6dLxXV126W2NZu5CxXlBus/Uw==,iv:nsiSa29cGwFVwsVGxpOcr/XUIkqFaaxThPZFjp4nyoc=,tag:oOfu9sKTg20KU3bKckmFiw==,type:str]
    JWT_PRIVATE_KEY: null
    JWT_PUBLIC_KEY: null
    GOOGLE_CLIENT_ID: ENC[AES256_GCM,data:J4a7mbwz2o7vGsK4tgyG1t17X4NfYls+oloN/cOUJd7GurVq6a+FLymmPq0/bAS7EHk0/wxDRuJWIcQfbOq39eMZhWHZY2vdXuT5+xHCtJUAu71r1UPKApB/lWQ3hIFw,iv:fFJ8u6jpKZALJfoyz1EAQGm2nGK2Y+6JhlO+emTk1is=,tag:hPedtap4X3LunMKt4BImTA==,type:str]
    GOOGLE_CLIENT_SECRET: ENC[AES256_GCM,data:s+63Bgyloge+p/midFcJm92rF7Vm8uTHnUjv2Ey2z/FOW2QFIOGScOrY8AxRYrcB,iv:KHgy8ezJebo5PbvDpQ6aY6Kkw0UgK0csH+aeDHuT3Nk=,tag:J+EJX4QrFaEXO88JBuahXg==,type:str]
kind: ENC[AES256_GCM,data:HtnfJsYr,iv:aNuk7nm+IdxHYpw1sYSYhVuHRpswxUcYGqQoyV0Aovs=,tag:IRVIGswfELb7TZrk3+Ofag==,type:str]
metadata:
    name: ENC[AES256_GCM,data:sAefiKKJ/DLZyJ88Q3l7Ywi7lg==,iv:9sa+/aXJ/n+gEoGWyX9RHcilYEVkKu00pjO5ItGqHek=,tag:5LVPcOQBhLyTWOLDqLOTxw==,type:str]
    namespace: ENC[AES256_GCM,data:NMdvc9dLyFgG,iv:VkpS66wfC7l1I8xQh/6peievG+d3K/GEBgOOQafoARA=,tag:Gksuj6dbei2IaqXwlBWeyg==,type:str]
sops:
    age:
        - recipient: age1dmaj620d54n0euwe2fz6lg2vvfkwwt7gtj6t5r9tqmsuj2ah0cpqg4dg7k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCUTBzTE5WbHdRaDV3VHdJ
            bzh5VXFFTFRTcmpJUm4wOG92Qkp4TzF3TVQwCmhlTmd1dXk0TW5UdFhwYlFsRlpD
            SzQycUY5ek1HM1dJQ3plZGF5ejFBczgKLS0tIG9CMktPeWhaVVYzUnVHbG8xT0Qz
            bTZzNE04eWhQcDRqdURWVG85aXMyK0UKX92PbuiLX1QgijBv4MZxbcn7FhnXBCWt
            d17EraQ/j5QhJDtHHw7Ogpa9NZszeLSKqPcNnre+d2nNHN6V9izArw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-03T03:02:10Z"
    mac: ENC[AES256_GCM,data:jNWkHJdi98HcoU+TmYNAyAFaysIGbjlPR/Wd3ubzjUZwYMSksQ13m6Fd1E4iIEwTO2XzwuGh/A1XvfjlflXPzjmLObgATIVT9j6hY33oznllr0BHAyAYdr5PWSRhYqQLP7fA6ViL+HbGFNA28+YYiQjdQVLwkzDyTo1x4Y1fVNc=,iv:gpEIsMITcnM4jhLqmKEHk7bi2rsfW7Mc/i+mVCIjFsY=,tag:VL2MGIb7yw9LRGKZTZyEZw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
