apiVersion: ENC[AES256_GCM,data:Ux4=,iv:8jqYyAtSz2HeFDSWiK2YVG+P4d9JANZyTXLzARmAY8w=,tag:FeEQ5oFn+rjeQbJH/hMwpA==,type:str]
data:
    DB_USERNAME: ENC[AES256_GCM,data:gg4atw==,iv:tvVPNQamg1t7Lz0auhUT4aDghKU8fFWnj5n0GJ6D2W8=,tag:/6+j3Y+QO4PJmd6oPbaP3w==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:9/8wKdiT8oZ/EyuXjJSW0fChV9LKwEK959m751rz8zOAp6ciLAFgZaud8Gi9clE9hCLDZlYdW7E96fPa+4hoNK2r1CVBdsp/Xo9v08mefu8Tk1Y/Co8/rg==,iv:qIlDgy4p7GnAvAKRSc532f8GtqU5DIc1NW03f9s5R4s=,tag:7owsF5CGgqW0jUPe8le1zA==,type:str]
    JWT_PRIVATE_KEY: null
    JWT_PUBLIC_KEY: null
    GOOGLE_CLIENT_ID: ENC[AES256_GCM,data:eq+Q2JdBicaJsjnTf4H60Bt61KL+Lh00Rr3unIwnPNK8vbOa+6iyTTUFrB/Y9AeINeoNyyn0RWdaVfVPY3vgGrcddtWevpI=,iv:AUyiMup+60m1rh/R5T3O6hTEq8OzPmMf/iiFeWjUbrY=,tag:IkL+6zjdJYL3cyhc2AFxpw==,type:str]
    GOOGLE_CLIENT_SECRET: ENC[AES256_GCM,data:cqTrNJoBM1dP38h8drjQNoPvhM4/r/xNhW/ioEzvf2s8cis=,iv:dxg2plGWU5FjDjZg5EJiXWX2wXbq4k1MeniajrOvVtY=,tag:p/K4pZ1HEp7cz1GUpQDt2Q==,type:str]
kind: ENC[AES256_GCM,data:Xlac0VNy,iv:xNMs2sQ8KYjYHp0S4jedFzKiu7Y9EAtcRhak4ZHQIjA=,tag:HcP7On2z4oqYaA3ToJMuCg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:K7t4fzL7EO6zFX4s6j1TM7bLwQ==,iv:jF+G7II7UH0t3Fafa+IrsUSBc7r5yUCu3ULbFQfYXbk=,tag:h5io+gGiDxsGC6Mz9Op7tQ==,type:str]
    namespace: ENC[AES256_GCM,data:OtLw7gRfBMuA,iv:6jnd2mPVjXS/qlkU24f09fvmOgtV9TjRSNhP7UmOZkI=,tag:WcACFNdqr0y1m53stUf6Ag==,type:str]
sops:
    age:
        - recipient: age1dmaj620d54n0euwe2fz6lg2vvfkwwt7gtj6t5r9tqmsuj2ah0cpqg4dg7k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0MTdHeWpFNTNmYWVwdTcz
            V3J0MnQ2VHdkVDVYUEVlQkJHZWQ3QTdIaUUwCno0bThPYlJaaEZEelk1WE0zUkdG
            VU5yOHRZNVZjVHYxaG1FdUM4RWFzTGMKLS0tIHkrVXlmL0VNazhDZDV6bjdXSWt6
            Z2c5Nkh2SUZNbFZocWxzbTdiZllLWjQKlsT2BMi8Bg8Jct55wjnFbTrMTkY1zxbi
            qHZUmVTy9Sd3OAvPY4BZFMizjC93YjpBwYNIyiRa3vfU/3EzGAOWSw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-03T02:58:08Z"
    mac: ENC[AES256_GCM,data:NqtMfdBInlU5wmE99d2C5pORRNYv5sSVcZGEyryigYPgOLpSJw8hkfUB1cc5+956Pd7pY/FWS9tZMh9ztvH2WevVMbWg8sKp67Bpgxyb7YVNcCyiNzrac1iQGV6gdoodOoMrQ1YFMFJdyVFw+zQTwksgFtnV1EmCFrfDeF6eIBE=,iv:1jxtezYo47iRucLg2cNpH4z0dmT4wmCxfHSEggHAY6A=,tag:xgthxfixSotrqs1+N+XW/A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
