apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: product-service-kubelet-probes
  namespace: ecommerce
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/instance: product-service
  ingress:
    - fromEntities:
        - host
        - remote-node
      toPorts:
        - ports:
            - port: "3001"
              protocol: TCP
